version: '3'

services:
    redis:
        restart: always
        image: redis
        networks:
            cartalog_network:
                ipv4_address: "10.30.20.20"
        ports:
            - "6379:6379"
    mongodb-pri:
        restart: always
        container_name: mongodb-pri
        command: ["mongod","-f","/etc/mongod.conf"]
        image: percona/percona-server-mongodb:5.0
        volumes:
            - mongodb-pri:/data/db
            - /home/vagrant/mongod.conf:/etc/mongod.conf
        networks:
            cartalog_network:
                ipv4_address: "10.30.20.10"
        ports:
            - "27017:27017"
    mongodb-sec:
        restart: always
        container_name: mongodb-sec
        command: ["mongod","-f","/etc/mongod.conf"]
        image: percona/percona-server-mongodb:5.0
        volumes:
            - mongodb-sec:/data/db
            - /home/vagrant/mongod.conf:/etc/mongod.conf
        networks:
            cartalog_network:
                ipv4_address: "10.30.20.11"
        ports:
            - "27018:27017"
    server:
        restart: always
        image: 76077e6/dev:2.0
        networks:
            cartalog_network:
                ipv4_address: "10.30.20.100"
        ports:
            - "22022:22"
            - "3000:3000"
    fleet-control:
        restart: always
        image: 76077e6/dev:2.0
        extra_hosts:
            - "bbhub.local:10.30.20.100"
        networks:
            cartalog_network:
                ipv4_address: "10.30.20.101"
        ports:
            - "22023:22"
            - "3001:3001"
    mqtt:
        restart: always
        image: eclipse-mosquitto
        volumes:
            - mosquitto_data:/mosquitto/data
            - mosquitto_log:/mosquitto/log
            - /home/vagrant/mqtt.conf:/mosquitto/config/mosquitto.conf
        ports:
            - "1883:1883"
            - "9001:9001"
        extra_hosts:
            - "bbhub.local:10.30.20.100"
        networks:
            cartalog_network:
                ipv4_address: "10.30.20.102"
networks:
    cartalog_network:
        ipam:
            driver: default
            config:
                - subnet: "10.30.20.0/24"
volumes:
    mongodb-pri:
        external: true
    mongodb-sec:
        external: true
    mongod.conf:
        external: true
    mqtt.conf:
        external: true
    mosquitto_data:
        external: true
    mosquitto_log:
        external: true
